name: self-confirming-transformer
channels:
- pytorch
dependencies:
- python=3.7
- anaconda
- cudatoolkit
- numpy
- pip
- pip:
  - gym==0.15.7
  - numpy==1.20.3
  - torch==1.8.1
  - transformers==4.5.1
